export const SalesReportTemplate = (filteredSales, totalSales, dateRange) => {
    const [startDate, endDate] = dateRange;
    const reportDate = new Date().toLocaleString();
    
    let dateRangeText = 'All Time';
    if (startDate && endDate) {
      dateRangeText = `${format(startDate, 'MMM d, yyyy')} to ${format(endDate, 'MMM d, yyyy')}`;
    }

    return `
    <div style="width: 100%; font-family: Arial, sans-serif; color: #000; padding: 30px; box-sizing: border-box; background-color: #ffffff; max-width: 800px; margin: 0 auto;">
      <div style="text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #4a6bdf;">
        <h1 style="color: #4a6bdf; margin: 0; font-size: 28px; font-weight: 700;">SHOPIQUE</h1>
        <p style="color: #666; margin: 5px 0 0 0; font-size: 14px;">Daily Sales Report</p>
      </div>

      <div style="margin-bottom: 25px; padding: 20px; border: 1px solid #e9ecef; border-radius: 8px; background-color: #f8f9fa;">
        <h3 style="margin: 0 0 15px 0; color: #333; font-size: 18px; border-bottom: 1px solid #e9ecef; padding-bottom: 10px;">Report Summary</h3>

        <div style="display: flex; margin-bottom: 15px;">
          <div style="width: 50%;">
            <p style="margin: 0 0 5px 0; font-size: 13px; color: #666;">Report Date</p>
            <p style="margin: 0; font-size: 16px; font-weight: 600;">${reportDate}</p>
          </div>
          <div style="width: 50%;">
            <p style="margin: 0 0 5px 0; font-size: 13px; color: #666;">Period Covered</p>
            <p style="margin: 0; font-size: 16px; font-weight: 600;">${dateRangeText}</p>
          </div>
        </div>

        <div style="display: flex; margin-bottom: 15px;">
          <div style="width: 50%;">
            <p style="margin: 0 0 5px 0; font-size: 13px; color: #666;">Total Transactions</p>
            <p style="margin: 0; font-size: 16px;">${filteredSales.length}</p>
          </div>
          <div style="width: 50%;">
            <p style="margin: 0 0 5px 0; font-size: 13px; color: #666;">Total Revenue</p>
            <p style="margin: 0; font-size: 16px;">₹${totalSales.toFixed(2)}</p>
          </div>
        </div>
      </div>

      <div style="margin-bottom: 25px;">
        <h3 style="margin: 0 0 15px 0; color: #333; font-size: 18px; border-bottom: 1px solid #e9ecef; padding-bottom: 10px;">Sales Transactions</h3>
        
        <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
          <thead>
            <tr style="background-color: #f8f9fa; border-bottom: 2px solid #e9ecef;">
              <th style="padding: 10px; text-align: left;">Bill No.</th>
              <th style="padding: 10px; text-align: left;">Product</th>
              <th style="padding: 10px; text-align: left;">Price</th>
              <th style="padding: 10px; text-align: left;">Qty</th>
              <th style="padding: 10px; text-align: left;">Total</th>
              <th style="padding: 10px; text-align: left;">Date</th>
            </tr>
          </thead>
          <tbody>
            ${filteredSales.map(sale => `
              <tr style="border-bottom: 1px solid #e9ecef;">
                <td style="padding: 10px;">${sale.billNumber}</td>
                <td style="padding: 10px;">${sale.productname}</td>
                <td style="padding: 10px;">₹${sale.price.toFixed(2)}</td>
                <td style="padding: 10px;">${sale.quantity}</td>
                <td style="padding: 10px;">₹${sale.totalAmount.toFixed(2)}</td>
                <td style="padding: 10px;">${formatDate(sale.soldAt)}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>

      <div style="margin-top: 30px; text-align: center; padding-top: 20px; border-top: 1px solid #e9ecef;">
        <p style="margin: 0; font-size: 16px; font-weight: 600; color: #333;">Shopique Sales Report</p>
        <p style="margin: 5px 0 0 0; font-size: 13px; color: #666;">Generated by Shopique POS System</p>
        <p style="margin: 5px 0 0 0; font-size: 12px; color: #999;">www.shopique.com | support@shopique.com</p>
      </div>
    </div>
    `;
  };